install_data(
  files(
    '__init__.py',
    'app_window.py',
    'file_manager.py',
    'input_manager.py',
    'monitor_handler.py',
    'session_manager.py',
    'tab_manager.py',
    'view_mode_manager.py',
    'find_controller.py',
    'zen_controller.py',
    'zoom_controller.py',
  ),
  install_dir: pythondir / 'markdown_vault' / 'app',
)
